export const messages = [
    {
        id: 1,
        roomId: 1,
        sender: 'Lisa Parker',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
    {
        id: 2,
        roomId: 1,
        sender: 'Anna Adame',
        message: 'Good morning, How are you? What about our next meeting?',
        createdAt: '09:08 am',
    },
    {
        id: 3,
        roomId: 1,
        sender: 'Lisa Parker',
        message: 'Yeah everything is fine. Our next meeting tomorrow at 10.00 AM',
        createdAt: '09:10 am',
    },
    {
        id: 4,
        roomId: 1,
        sender: 'Lisa Parker',
        message: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.",
        createdAt: '09:10 am',
    },
    {
        id: 5,
        roomId: 1,
        sender: 'Anna Adame',
        message: "Wow that's great",
        createdAt: '09:12 am',
    },
    {
        id: 6,
        roomId: 2,
        sender: 'Frank Thomas',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
    {
        id: 7,
        roomId: 3,
        sender: 'Clifford Taylor',
        message: 'Hello 😊',
        createdAt: '09:07 am',
    },
    {
        id: 8,
        roomId: 4,
        sender: 'Janette Caster',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
    {
        id: 9,
        roomId: 5,
        sender: 'Sarah Beattie',
        message: 'Hii 😊',
        createdAt: '09:07 am',
    },
    {
        id: 10,
        roomId: 6,
        sender: 'Nellie Cornett',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
    {
        id: 11,
        roomId: 7,
        sender: 'Chris Kiernan',
        message: 'How Are You 😊',
        createdAt: '09:07 am',
    },
    {
        id: 12,
        roomId: 8,
        sender: 'Edith Evans',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
    {
        id: 13,
        roomId: 9,
        sender: 'Joseph Siegel',
        message: 'Good morning 😊',
        createdAt: '09:07 am',
    },
];
