export const taskWidgets = [
    {
        id: 1,
        label: 'Qarzdorlar',
        counter: '234',
        badge: 'ri-arrow-up-line',
        badgeClass: 'success',
        percentage: '17.32 %',
        icon: 'bx bx-dollar-circle',
        iconClass: 'danger',
        decimals: 1,
        prefix: '',
        suffix: 'k',
    },
    {
        id: 2,
        label: "Muddatli to'lov",
        counter: '64.5',
        badge: 'ri-arrow-down-line',
        badgeClass: 'danger',
        percentage: '0.87 %',
        icon: 'ri-wallet-3-line',
        iconClass: 'warning',
        decimals: 1,
        prefix: '',
        suffix: 'k',
    },
    {
        id: 3,
        label: 'Ipoteka',
        counter: '116.21',
        badge: 'ri-arrow-down-line',
        badgeClass: 'danger',
        percentage: '2.52 %',
        icon: 'ri-bank-line',
        iconClass: 'primary',
        decimals: 2,
        prefix: '',
        suffix: 'K',
    },
];
